In [1]:
%load_ext autoreload
%autoreload 2
import torch
import torch.nn as nn
from cfg.configs import Config
from util.args import parse_args
import numpy as np
import scipy.optimize as op
from data.data import SphericalDataset, SphericalBlockDataset, minmax_scale, normalization
from eval.util import mse, mae
from train import load_checkpoint, load_checkpoint_block
from time import time
from data.vec_io import *
from data.vis_io import *
from util.phys2comp import *

### Rooting Finding: phys -> comp

In [84]:
import numpy as np

def deg2rad(deg):
  return deg * np.pi / 180

# for numerical isse
def mysin(a):
  val = np.sin(a)
  val = close_round(val, 0)
  val = close_round(val, 1)
  return val

def mycos(a):
  val = np.cos(a)
  val = close_round(val, 0)
  val = close_round(val, 1)
  return val

def close_round(val, test_val, abs_bounds=1e-12):
  isclose = np.abs(test_val - val) < abs_bounds
  # print(isclose)
  if isinstance(val, float) or isinstance(val, int) or np.float32:
    val_cp = test_val if isclose else val
  else:
    val_cp = val.copy()
    val_cp[isclose] = test_val
  return val_cp

def sph2car(r, theta, phi):
  # x_coef = np.sin(phi)*np.cos(theta)
  # y_coef = np.around(np.sin(phi)*np.sin(theta), decimals=10)
  # z_coef = np.around(np.cos(phi), decimals=10)
  x = r*mysin(phi)*mycos(theta)
  y = r*mysin(phi)*mysin(theta)
  z = r*mycos(phi)
  
  return np.array([x,y,z])

def car2sph(x, y, z):
  # assert (x or y) != 0
  r = np.sqrt(x*x + y*y + z*z)
  theta = np.arctan(y/x)
  phi = np.arctan(np.sqrt(x*x + y*y) / z)
  # if x > 0:
  #   phi = np.arctan(y/x)
  # elif x < 0 and y >= 0:
  #   phi = np.arctan(y/x)+np.pi
  # elif x < 0 and y < 0:
  #   phi == np.arctan(y/x)-np.pi
  # elif x == 0 and y > 0:
  #   phi = np.pi/2
  # elif x == 0 and y < 0:
  #   phi = -np.pi/2

  return np.array([r,theta,phi])
# //
# //		    6________7  high-vtx
# //		   /|       /|
# //		  / |      / |
# //		4/_______5/  |
# //		|  2|___ |___|3
# //		|  /     |  /
# //		| /      | /
# //		|/_______|/
# //		0        1
# //  low_vtx

# //
# //		 011_________111  high-vtx
# //		   /|       /|
# //		  / |      / |
# //	001/_____101/  |
# //		|010|___ |___|110
# //		|  /     |  /
# //		| /      | /
# //		|/_______|/
# //	000       100

# //
# //		    8________7  high-vtx
# //		   /|       /|
# //		  / |      / |
# //		5/_______6/  |
# //		|  4|___ |___|3
# //		|  /     |  /
# //		| /      | /
# //		|/_______|/
# //		1        2
# //  low_vtx

def trilerp(coord: np.ndarray, low_vtx: np.ndarray, high_vtx: np.ndarray, cell_val: np.ndarray):
  # x0,y0,z0 = low_vtx
  # x1,y1,z1 = high_vtx
  # x, y, z = coord

  # low_vtx, high_vtx, coord = normalization(np.array([low_vtx, high_vtx, coord]), new_min=0, dim=0)

  # TODO: Why trilerp doesn't work if low and high are not normalized to 1
  # print(coord, low_vtx, high_vtx)
  # print(coord)
  x, y, z = (coord - low_vtx) / (high_vtx - low_vtx)
  # print(x,y,z)
  # low_vtx = np.zeros(3)
  # high_vtx = np.ones(3)
  # x0,y0,z0 = low_vtx
  # x1,y1,z1 = high_vtx

  v000 = cell_val[0,0,0]
  v100 = cell_val[1,0,0]
  v010 = cell_val[0,1,0]
  v110 = cell_val[1,1,0]
  v001 = cell_val[0,0,1]
  v101 = cell_val[1,0,1]
  v011 = cell_val[0,1,1]
  v111 = cell_val[1,1,1]
  # print(x, y, z)
  # print(x0, y0, z0)
  # print(x1, y1, z1)
  # print((x0-x1)*(y0-y1)*(z0-z1))
  # print(((x0-x1)*(y0-y1)*(z0-z1)))
  # for cord in [v000, v100, v010, v110, v001, v101, v011, v111]:
  #   print(cord)
  
  # a0 = (
  #   (-v000*x1*y1*z1 + v001*x1*y1*z0 + v010*x1*y0*z1 - v011*x1*y0*z0 + 
  #   v100*x0*y1*z1 - v101*x0*y1*z0 - v110*x0*y0*z1 + v111*x0*y0*z0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a1 = (
  #   (v000*z1*y1 - v001*z0*y1 - v010*z1*y0 + v011*z0*y0 - 
  #   v100*z1*y1 + v101*z0*y1 + v110*z1*y0 - v111*z0*y0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a2 = (
  #   (v000*x1*z1 - v001*x1*z0 - v010*x1*z1 + v011*x1*z0 - 
  #   v100*x0*z1 + v101*x0*z0 + v110*x0*z1 - v111*x0*z0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a3 = (
  #   (v000*x1*y1 - v001*x1*y1 - v010*x1*y0 + v011*x1*y0 - 
  #   v100*x0*y1 + v101*x0*y1 + v110*x0*y0 - v111*x0*y0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a4 = (
  #   (-v000*z1 + v001*z0 + v010*z1 - v011*z0 + 
  #   v100*z1 - v101*z0 - v110*z1 + v111*z0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a5 = (
  #   (-v000*y1 + v001*y1 + v010*y0 - v011*y0 + 
  #   v100*y1 - v101*y1 - v110*y0 + v111*y0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a6 = (
  #   (-v000*x1 + v001*x1 + v010*x1 - v011*x1 + 
  #   v100*x0 - v101*x0 - v110*x0 + v111*x0)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  # a7 = (
  #   (v000 - v001 - v010 + v011 -v100 + v101 + v110 - v111)
  # )/ ((x0-x1)*(y0-y1)*(z0-z1))
  
  
  # //
  # //		    8________7  high-vtx
  # //		   /|       /|
  # //		  / |      / |
  # //		5/_______6/  |
  # //		|  4|___ |___|3
  # //		|  /     |  /
  # //		| /      | /
  # //		|/_______|/
  # //		1        2
  # //  low_vtx

  #   [v000, v100, v110, v010,
  #  v001, v101, v111, v011,]
  a0 = v000
  a1 = -v000 + v100
  a2 = -v000 + v010
  a3 = -v000 + v001
  a4 = v000 - v100  + v110 - v010
  a5 = v000 - v100 - v001 + v101
  a6 = v000 - v010 - v001 + v011
  a7 = -v000 +v100 -v110 +v010 +v001 -v101 +v111 -v011

  interpolant = (a0 + a1*x + a2*y + a3*z + a4*x*y + a5*x*z + a6*y*z + a7*x*y*z)
  coeff = np.array([a0, a1, a2, a3, a4, a5, a6, a7]).T
  # coeff1 = np.array([aa0, aa1, aa2, aa3, aa4, aa5, aa6, aa7]).T
  # print(coeff == coeff1)
  # print(coeff)
  # print(coeff1)
  return interpolant, coeff

# G
def comp2phys(comp: np.ndarray, vtx_low, vtx_high, cell_coords):
  phys_est_x, a = trilerp(comp, vtx_low, vtx_high, cell_coords[..., 0])
  phys_est_y, b = trilerp(comp, vtx_low, vtx_high, cell_coords[..., 1])
  phys_est_z, c = trilerp(comp, vtx_low, vtx_high, cell_coords[..., 2])
  return np.array([phys_est_x, phys_est_y, phys_est_z]), np.array([a,b,c])

# F
def diff_phys(comp: np.ndarray, phys: np.ndarray, vtx_low, vtx_high, cell_coords):
  phys_est, coeff = comp2phys(comp, vtx_low, vtx_high, cell_coords)
  return phys - phys_est

def diff_phys_dim(comp: np.ndarray, phys: np.ndarray, vtx_low, vtx_high, cell_coords_dim):
  phys_est = trilerp(comp, vtx_low, vtx_high, cell_coords_dim)
  return phys - phys_est
# op.root_scalar(diff_phys, method='newton')

def diff_phys_dim_inv_jac():
  pass

class CurviInterpField:
  def __init__(self):
    pass

class CurviInterpCell:
  def __init__(self, min_comp, max_comp, phys_coords):
    self.min_comp = np.array(min_comp)
    self.max_comp = np.array(max_comp)
    self.phys = phys_coords
    self.init_comp = min_comp + (max_comp - min_comp) / 2
    self.coeff = None

    # xs = [min_comp[0], max_comp[0]]
    # ys = [min_comp[1], max_comp[1]]
    # zs = [min_comp[2], max_comp[2]]
    # self.interp = RegularGridInterpolator((xs, ys, zs), phys_coords)

  # Newton's method to find computational coordinate given physical cooridnate
  def phys2comp(self, phys: np.ndarray, init_comp=None, tol=1.48e-8, maxiter=50, rtol=0.0):
    if init_comp is None:
      init_comp = self.init_comp

    comp = init_comp
    goal_diff = np.zeros(3)
    for i in range(maxiter):
      phys_est, coeff = self.comp2phys(comp)
      diff_funcval = (phys_est - phys)

      jac_inv = self.get_jacobian_inv(comp, coeff)

      new_comp = comp - (jac_inv @ diff_funcval.reshape(3, 1)).flatten()
      # print("My Jac inv\n", jac_inv, diff_funcval, "\n")
      # print(phys_est.shape, coeff.shape, phys.shape)
      # print(new_comp.shape, comp.shape)
      # print(jac_inv.shape, diff_funcval.shape)
      # print(f'coeff: {coeff[:, 0]}')
      print(f'phys_est: {phys_est} comp: {new_comp}  error: {np.abs(diff_funcval-goal_diff)}')
      # if np.all(np.isclose(new_comp, comp, rtol=rtol, atol=tol)):
      if np.all(np.isclose(diff_funcval, goal_diff, rtol=rtol, atol=tol)):
        print(f'iter {i}')
        return new_comp
      comp = new_comp
    return comp

  # def phys2comp(self, phys):
  #   return self.find_comp(phys)

  def comp2phys(self, comp):
    phys_est, coeff = trilerp(comp, self.min_comp, self.max_comp, self.phys)
    # phys_est_y, b = trilerp(comp, self.min_comp, self.max_comp, self.phys[..., 1])
    # phys_est_z, c = trilerp(comp, self.min_comp, self.max_comp, self.phys[..., 2])
    # self.coeff = np.array([a,b,c])
    # return np.array([phys_est_x, phys_est_y, phys_est_z]), np.array([a,b,c])
    # print(phys_est.shape, coeff.shape)
    # self.interp(comp)
    return phys_est, coeff
  
  def get_jacobian(self, comp, coeff):
    a,b,c = coeff
    # print("COE: \n", coeff.T)
    print("My COMP: \n", comp)
    return np.array([
      [
        a[1] + a[4]*comp[1] + a[5]*comp[2] + a[7]*comp[1]*comp[2],
        a[2] + a[4]*comp[0] + a[6]*comp[2] + a[7]*comp[0]*comp[2],
        a[3] + a[5]*comp[0] + a[6]*comp[1] + a[7]*comp[0]*comp[1],
      ],
      [
        b[1] + b[4]*comp[1] + b[5]*comp[2] + b[7]*comp[1]*comp[2],
        b[2] + b[4]*comp[0] + b[6]*comp[2] + b[7]*comp[0]*comp[2],
        b[3] + b[5]*comp[0] + b[6]*comp[1] + b[7]*comp[0]*comp[1],
      ],
      [
        c[1] + c[4]*comp[1] + c[5]*comp[2] + c[7]*comp[1]*comp[2],
        c[2] + c[4]*comp[0] + c[6]*comp[2] + c[7]*comp[0]*comp[2],
        c[3] + c[5]*comp[0] + c[6]*comp[1] + c[7]*comp[0]*comp[1],
      ]
    ])
  
  def get_jacobian_inv(self, comp, coeff):
    # print(comp)
    comp = (comp - self.min_comp) / (self.max_comp - self.min_comp)
    # print(comp)
    
    jac = self.get_jacobian(comp, coeff)
    np_det = np.linalg.det(jac)
    np_inv = np.linalg.inv(jac)
    # det = (-jac[0,0]*jac[1,1]*jac[2,2] - jac[0,1]*jac[1,2]*jac[2,0] - jac[0,2]*jac[1,0]*jac[2,1] + 
    #         jac[0,2]*jac[1,1]*jac[2,0] + jac[0,1]*jac[1,0]*jac[2,2] + jac[0,0]*jac[1,2]*jac[2,1])
    det = np_det
    inv = np.array([
      [
        jac[1,1]*jac[2,2] - jac[1,2]*jac[2,1],
        -jac[0,1]*jac[2,2] + jac[0,2]*jac[2,1],
        jac[0,1]*jac[1,2] - jac[0,2]*jac[1,1],
      ],
      [
        -jac[1,0]*jac[2,2] + jac[1,2]*jac[2,0],
        jac[0,0]*jac[2,2] - jac[0,2]*jac[2,0],
        -jac[0,0]*jac[1,2] + jac[0,2]*jac[1,0],
      ],
      [
        jac[1,0]*jac[2,1] - jac[1,1]*jac[2,0],
        jac[0,0]*jac[2,1] - jac[0,1]*jac[2,0],
        jac[0,0]*jac[1,1] - jac[0,1]*jac[1,0],
      ],
    ])
    
    # print("jac, np_inv, inv\n", jac)
    # print(np_inv, inv/det)
    # print(inv)
    # print(inv/det)
    # print(np_det)
    # print(f"det {-det}")
    det = np_det
    inv = np_inv
    # print("My Jac inv\n", jac, "\n", inv, det, "\n")
    return inv

In [5]:
# Small runtime test
compMat = comp.reshape(-1, 3)
low_vtx = comp[0,0,0]
high_vtx = comp[1,1,1]
# low_vtx = np.zeros(3)
# high_vtx = np.ones(3)
init_guess = (low_vtx + high_vtx) / 2

st = time()
cic = CurviInterpCell(min_comp=low_vtx, max_comp=high_vtx, phys_coords=phys)
print(f"Testing point in phys is { point_phys}")
print(f"Testing point in comp GT is { point}")
print(f"Testing point initial phys_est is {cic.comp2phys(init_guess)[0]}\n\n")

num_iter = 1
for i in range(num_iter):
  comp_est_newton = cic.phys2comp(point_phys, maxiter=20, tol=1e-4)
t_newton = time() - st

print(f"GT phys: {point_phys}")
phys_est = trilerp(comp_est_newton, low_vtx, high_vtx, phys)[0]
phys_norm = ds.inpp.transform(point_phys)
phys_est_norm = ds.inpp.transform(phys_est)
print(f"newton prediction to phys: {phys_est}, normalized error: {mse(phys_norm, phys_est_norm)}, time: {t_newton} sec")
# print(f"NN     prediction: {comp_est_nn}, normalized error: {mse(comp_est_nn_norm, point_norm)}, time: {t_nn} sec")

Testing point in phys is [ -768.3575  4154.1406 -2542.9346]
Testing point in comp GT is [4930.9       100.4791    121.045204]
Testing point initial phys_est is [ -788.2637  4140.097  -2567.425 ]


comp low high: [4928.       100.27855  120.843  ] [4942.5       101.281334  121.854   ]
My Jac inv
 [[-1.1017113e-02  5.7863098e-02 -3.5880320e-02]
 [-1.3317657e-02 -2.5356503e-03  8.1919183e-10]
 [ 1.1174238e-03  5.8688335e-03 -9.8070344e-03]] [-19.906189 -14.043457 -24.490479] [ -788.2637  4140.097  -2567.425 ]
 diff_comp, comp: [0.285437   0.30071306 0.13551661] [4935.25      100.77994   121.348495]

My Jac inv
 [[-1.1017130e-02  5.7863105e-02 -3.5880361e-02]
 [-1.3312557e-02 -2.4623412e-03 -4.9904592e-09]
 [ 1.1131512e-03  5.8463849e-03 -9.8217279e-03]] [  0.76330566  -4.1757812  -14.374023  ] [ -767.5942  4149.965  -2557.3086]
 diff_comp, comp: [2.65712053e-01 1.20719917e-04 1.17614195e-01] [4934.9644    100.479225  121.21298 ]

My Jac inv
 [[-1.1017147e-02  5.7863113e-02 -3.5880372e-02]

In [13]:
bds = SphericalBlockDataset('data/earth_nopole.npy', [0,1,2], [3,4,5], downscale=2)
for curv_block, trans in bds.curvs:
  # curv_block = pp.inverse_transform(curv_block)
  print(curv_block.shape, curv_block.min(0)[0], curv_block.max(0)[0])

print(bds.block_indices.shape)
print(bds.block_indices[0])

transforming inputs
transforming targets
creating train test splits for inputs
creating train test splits for targets
(1440000, 3) 0.7092704 1.0
(1440000, 3) 0.70927036 1.0
(1440000, 3) 0.7038147 1.0
(1440000, 3) 0.70870084 1.0
(1440000, 3) 0.77438617 1.0
(1440000, 3) 0.77438617 1.0
(1440000, 3) 0.77113116 1.0
(1440000, 3) 0.774045 1.0
(8, 3, 2)
[[  0 100]
 [  0 180]
 [  0  80]]


In [14]:
cfgObj = Config('nntest_block_half.yaml')
nncfg = Config('nn_block_half.yaml')
testcfg = cfgObj.config
# get model
model_path = testcfg['model_path']
ckpt = load_checkpoint_block(model_path, nncfg)
models = ckpt['models']
for model in models:
  model.eval()
print()

FileNotFoundError: [Errno 2] No such file or directory: 'log/coord_mlp_block_half/ckpt_9702_0000_1.35e-06'

In [ ]:

i,j,k = 0,0,0
blocki = bds.get_block_index(i, j, k, bds.block_indices)

_, phys_trans = bds.carts[blocki]
_, comp_trans = bds.curvs[blocki]
phys0 = bds.cart[i,j,k]
comp0 = bds.curv[i,j,k].numpy()

phys0_input = torch.tensor(phys_trans.transform(phys0.numpy()))
model = models[blocki]
with torch.no_grad():
  # phys0_input = phys0_input[None]
  comp_pred0 = model(phys0_input).detach().cpu().numpy()
comp_pred0 = comp_trans.inverse_transform(comp_pred0)

display(comp_pred0, comp0, mse(comp_pred0, comp0))

array([3485.7607  ,   21.173586,  165.57495 ], dtype=float32)

array([3485.   ,    0.   ,  170.393], dtype=float32)

157.37105

In [2]:
cfgObj = Config('nntest.yaml')
nncfg = Config('nn.yaml')
testcfg = cfgObj.config

ds = nncfg.get_dataset()

# get model
model_path = testcfg['model_path']
ckpt = load_checkpoint(model_path, nncfg)
model = ckpt['model']
model.eval()
print()

transforming inputs
transforming outputs



In [3]:
xyz = read_vec('../test/src/data/mantle_phys.vec')
xg, yg, zg = read_grid('../test/src/data/mantle_comp.grid')
xyz_comp = get_mesh(xg, yg, zg)
ds.cart = xyz
ds.curv = xyz_comp

meshe generated: (201, 360, 140, 3)


In [4]:
phys = np.array(ds.cart[100:102, 100:102, 100:102])
comp = np.array(ds.curv[100:102, 100:102, 100:102])
# phi dimension is decressing, which breaks trilerp implementation
# comp = np.flip(comp, 2)
# phys_calc = np.array([sph2car(sph[0], *np.radians(sph[1:])) for sph in comp.reshape(-1, 3)]).reshape(2,2,2,3)


# get the mean coordinate as initial guess
init_guess = comp.reshape(-1, 3).mean(0)

init_guess

low_vtx = comp[0,0,0]
high_vtx = comp[1,1,1]
xs = [low_vtx[0], high_vtx[0]]
ys = [low_vtx[1], high_vtx[1]]
zs = [low_vtx[2], high_vtx[2]]

cell_coords_x, cell_coords_y, cell_coords_z = np.meshgrid(
  xs, ys, zs, indexing='ij',  sparse=False
)


point = low_vtx + (high_vtx - low_vtx)*0.2
# point[0] *= 0.2
# point[1] *= 0.5
# point[2] *= 0.92
display(low_vtx, high_vtx)

point_phys = sph2car(point[0], *np.radians(point[1:]))
print(f"Testing point in phys is { point_phys}")
print(f"Testing point in comp GT is { point}")


array([4928.     ,  100.27855,  120.843  ], dtype=float32)

array([4942.5     ,  101.281334,  121.854   ], dtype=float32)

Testing point in phys is [ -768.3575  4154.1406 -2542.9346]
Testing point in comp GT is [4930.9       100.4791    121.045204]


In [62]:
point_phys

array([ -768.3575,  4154.1406, -2542.9346], dtype=float32)

In [20]:
i,j,k = 50,12,2
phys0 = ds.cart[i,j,k]
phys_trans = ds.inpp
comp_trans = ds.outpp
phys0_input = torch.tensor(phys_trans.transform(phys0))
with torch.no_grad():
  # phys0_input = phys0_input[None]
  comp_pred0 = model(phys0_input).detach().cpu().numpy()
comp_pred0 = comp_trans.inverse_transform(comp_pred0)
comp0 = ds.curv[i,j,k]
display(comp_pred0, comp0, mse(comp_pred0, comp0))

array([ 34982.87 , -11178.128, -10468.909], dtype=float32)

array([4202.87    ,   12.033426,   21.742   ], dtype=float32)

394227300.0

In [30]:
# Small runtime test
low_vtx = np.zeros(3)
high_vtx = np.ones(3)
init_guess = high_vtx / 2
cic = CurviInterpCell(min_comp=low_vtx, max_comp=high_vtx, phys_coords=phys)
print(f"Testing point in phys is { point_phys}")
print(f"Testing point in comp GT is { point}")
print(f"Testing point initial phys_est is {cic.comp2phys(init_guess)[0]}\n\n")
st = time()
cic = CurviInterpCell(min_comp=low_vtx, max_comp=high_vtx, phys_coords=phys)

num_iter = 1
for i in range(num_iter):
  comp_est_newton = cic.phys2comp(point_phys, maxiter=5, tol=1e-4)
t_newton = time() - st

# st = time()
# for i in range(num_iter):
#   point_phys_nn = ds.inpp.transform(point_phys)
#   with torch.no_grad():
#     comp_est_nn = model(torch.Tensor(point_phys_nn))
#   comp_est_nn = ds.outpp.inverse_transform(comp_est_nn.numpy())
# t_nn = time() - st

print(f"GT phys: {point_phys}")
phys_est = trilerp(comp_est_newton, low_vtx, high_vtx, phys)[0]
phys_norm = ds.inpp.transform(point_phys)
phys_est_norm = ds.inpp.transform(phys_est)
print(f"newton prediction to phys: {phys_est}, normalized error: {mse(phys_norm, phys_est_norm)}, time: {t_newton} sec")
# print(f"NN     prediction: {comp_est_nn}, normalized error: {mse(comp_est_nn_norm, point_norm)}, time: {t_nn} sec")

Testing point in phys is [ 587.40845  706.02    -359.21857]
Testing point in comp GT is [986.18     50.23955 111.36159]
Testing point initial phys_est is [ -788.26385  4140.097   -2567.4253 ]


phys_est: [ -788.26385  4140.097   -2567.4253 ] comp: [-292.5934574    -9.11310727  -39.77277987]  error: [1375.67236328 3434.07714844 2208.20678711]
phys_est: [-15.190887 898.5031    59.32617 ] comp: [-304.65880364  -49.44396257    2.02377783]  error: [602.59936523 192.48309326 418.54473877]
phys_est: [ 286.90683  481.32812 -277.30463] comp: [-292.45113029  -75.82975246   19.0969848 ]  error: [300.50161743 224.69189453  81.91394043]
phys_est: [ 515.6719   398.15363 -550.30896] comp: [-293.10218632  -68.4248436    21.35684943]  error: [ 71.73657227 307.86639404 191.09039307]
phys_est: [ 435.2812   359.32794 -565.84045] comp: [-292.54777335  -69.03252938   24.37361622]  error: [152.1272583  346.69207764 206.62188721]
GT phys: [ 587.40845  706.02    -359.21857]
newton prediction to phys: [ 424.275

In [10]:
xg, yg ,zg = np.meshgrid([0,1], [0,1], [0,1],indexing='ij',  sparse=True)
def f(x,y,z):
  return x + 10*y + 100*z
# my lerp
coord = [0.215, 0.282, 0.2162]
low_vtx = np.array([-1,-2,-3])
high_vtx = np.array([1,2,3])
cell_val = f(xg, yg, zg)
interpolant = trilerp(coord, low_vtx, high_vtx, cell_val)
gt = f(*coord)
print(f"gt: {gt}    -      lerp: {interpolant}")

0.6075 0.5705 0.5360333333333334
[ True  True  True  True  True  True  True  True]
[ -0.   1.  10. 100.  -0.  -0.  -0.  -0.]
[  0   1  10 100   0   0   0   0]
gt: 24.655    -      lerp: (59.91583333333334, array([ -0.,   1.,  10., 100.,  -0.,  -0.,  -0.,  -0.]))


In [58]:
# SCIPY lerp
from scipy.interpolate import RegularGridInterpolator

# x = np.arange(2)
# y = np.arange(2)
# z = np.arange(2)
# xg, yg ,zg = np.meshgrid(x, y, z, indexing='ij', sparse=True)
# data = f(xg, yg, zg)

x= comp[...,0][:,0,0]
y= comp[...,1][0,:,0]
z= comp[...,2][0,0,:]

xs = [low_vtx[0], high_vtx[0]]
ys = [low_vtx[1], high_vtx[1]]
zs = [low_vtx[2], high_vtx[2]]

my_interpolating_function = RegularGridInterpolator((xs, ys, zs), cell_val)
my_interpolating_function(coord)

array([59.91583333])